### PR TITLE
lmu2png: Add wxWidgets GUI

### PR DESCRIPTION
**Pull request by carstene1ns**
used

Also, multiple RTP dirs are now supported (like in Player).

### CODE REVIEW

**Comment by Ghabry** [comment]
That is great!

I almost got this to build on Windows for testing :) (wx builds fine with vcpkg, but there is a problem with this ancient SDL_image.cmake file we use, fix in progress)

**Comment by carstene1ns** [comment]
I have a local branch that replaces SDL with freeimage, not finished yet though.
Made a minimal fork to use on jenkins, but of course compatible with distro packages.

https://github.com/carstene1ns/freeimage-easyrpg

**Comment by Ghabry** [comment]
Ah okay in that case I can skip the work on fixing cmake :)

**Review by fdelapena — APPROVED** [review]

**Comment by Ghabry** [comment]
Saving fails with "no image handler for type 15" defined but rendering works...

Image becomes glitched when resizing the window.

grafik

**Comment by Ghabry** [comment]
To fix PNG saving you must call ``wxImage::AddHandler(new wxPNGHandler);`` once, e.g. on startup. Weird this isn't needed on Linux as the doc says only the BMP handler is loaded by default.

Cleanup is not necessary:

> A heap-allocated handler object which will be deleted by [wxImage](https://docs.wxwidgets.org/latest/classwx_image.html) if it is removed later by [RemoveHandler()](https://docs.wxwidgets.org/latest/classwx_image.html#a70ef86ff481bc18c0a32f5467a071e42) or at program shutdown.

**Comment by Ghabry** [comment]
Jenkins: test this please

**Comment by Ghabry** [comment]
@carstene1ns this obviously has some conflicts now but freeimage and wx on Windows should be working now :)

**Comment by carstene1ns** [comment]
Yeah, will adapt this sometime in the next days.

**Comment by carstene1ns** [comment]
Please test, it works for me™

**Comment by Ghabry** [comment]
Impressive error message from Windows global namespace pollution. Have to boot Windows to figure this mess out >.>

**Pull request merged**
