### PR TITLE
CMake: 2nd try

### PR DESCRIPTION
**Pull request by Ghabry**
Fixes the incorrect setting of /Ehsc as explained earlier.

Also setting Unicode by default now and disabling "this api is insecure" warnings.
Shared and static runtime library can be configured now.

Will use that helper in all our repos from now on, sad that CMake doesn't have this built-in.

Sorry for the huge SDL2[image].cmake change again. Looks like I messed up and reverted the files one commit after I updated them :/, sorry. (or forgot git add, no idea).

Tested building under Windows and Linux.
Going to test MacOS tomorrow.

### CODE REVIEW

**Comment by Ghabry** [comment]
Under MacOS I get weird linker errors concerning icu 59 symbols but both liblcf and the Tools are compiled against the 61 from brew. o.O

**Comment by Ghabry** [comment]
Builds & Links now under MacOS. Same problem as usual: SDL2 would be responsible to list the required frameworks via a cmake-config, not me :/

**Comment by Ghabry** [comment]
don#t merge yet, need to fix the static SDL2 linux/unix build via pkg-config foo

**Comment by carstene1ns** [comment]
We will need `libz` in `lmu2png/CMakeLists.txt` after #35.

**Comment by carstene1ns** [comment]
This one should be ready, right?

**Comment by Ghabry** [comment]
Yepp

**Pull request merged**
